// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HandMade_Store_api.Models;

public partial class ProductImage
{
    public int ImageId { get; set; }

    public int ProductId { get; set; }

    public string Url { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Product Product { get; set; }
}